#!/bin/bash

env > "${HOME}/env"

(
  /usr/local/bin/install-openshift-clients
  ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman
  ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker
  [ -x /usr/local/bin/podman ] \
    && [ ! -f "${HOME}/.zshrc.podman" ] \
    && sudo -u "${USER}" podman completion zsh > "${HOME}/.zshrc.podman"
  [ ! -f "${HOME}/.zshrc.oc" ] \
    && sudo -u "${USER}" oc completion zsh > "${HOME}/.zshrc.oc"
  [ ! -f "${HOME}/.zshrc.helm" ] \
    && sudo -u "${USER}" helm completion zsh > "${HOME}/.zshrc.helm"
)&

CONFS="tmux.conf zshrc p10k.zsh"
CONF_DIR="${CONF_DIR:-/usr/local/share/base-shell}"

for conf in $CONFS
do
  [ ! -e "${HOME}/.${conf}" ] && sudo -u "${USER}" cp "${CONF_DIR}/${conf}" "${HOME}/.${conf}"
done

[ ! -d "${HOME}/.oh-my-zsh" ] && sudo -u "${USER}" git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

[ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ] \
  && sudo -u "${USER}" rsync -av "${CONF_DIR}/powerlevel10k" "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/"

sudo -u "${USER}" chsh -s /usr/bin/zsh

wait

sudo -u "${USER}" exec zsh
